	sys_read,
	sys_write,
	sys_open,
	sys_close,
	sys_newstat,
	sys_newfstat,
	sys_newlstat,
	sys_poll,
	/* 8 */
	sys_lseek,
	sys_mmap,
	sys_mprotect,
	sys_munmap,
	sys_brk,
	sys_rt_sigaction,
	sys_rt_sigprocmask,
	stub_rt_sigreturn,
	/* 16 */
	sys_ioctl,
	sys_pread64,
	sys_pwrite64,
	sys_readv,
	sys_writev,
	sys_access,
	sys_pipe,
	sys_select,
	/* 24 */
	sys_sched_yield,
	sys_mremap,
	sys_msync,
	sys_mincore,
	sys_madvise,
	sys_shmget,
	sys_shmat,
	sys_shmctl,
	/* 32 */
	sys_dup,
	sys_dup2,
	sys_pause,
	sys_nanosleep,
	sys_getitimer,
	sys_alarm,
	sys_setitimer,
	sys_getpid,
	/* 40 */
	sys_sendfile64,
	sys_socket,
	sys_connect,
	sys_accept,
	sys_sendto,
	sys_recvfrom,
	sys_sendmsg,
	sys_recvmsg,
	/* 48 */
	sys_shutdown,
	sys_bind,
	sys_listen,
	sys_getsockname,
	sys_getpeername,
	sys_socketpair,
	sys_setsockopt,
	sys_getsockopt,
	/* 56 */
	stub_clone,
	stub_fork,
	stub_vfork,
	stub_execve,
	sys_exit,
	sys_wait4,
	sys_kill,
	sys_newuname,
	/* 64 */
	sys_semget,
	sys_semop,
	sys_semctl,
	sys_shmdt,
	sys_msgget,
	sys_msgsnd,
	sys_msgrcv,
	sys_msgctl,
	/* 72 */
	sys_fcntl,
	sys_flock,
	sys_fsync,
	sys_fdatasync,
	sys_truncate,
	sys_ftruncate,
	sys_getdents,
	sys_getcwd,
	/* 80 */
	sys_chdir,
	sys_fchdir,
	sys_rename,
	sys_mkdir,
	sys_rmdir,
	sys_creat,
	sys_link,
	sys_unlink,
	/* 88 */
	sys_symlink,
	sys_readlink,
	sys_chmod,
	sys_fchmod,
	sys_chown,
	sys_fchown,
	sys_lchown,
	sys_umask,
	/* 96 */
	sys_gettimeofday,
	sys_getrlimit,
	sys_getrusage,
	sys_sysinfo,
	sys_times,
	sys_ptrace,
	sys_getuid,
	sys_syslog,
/* at the very end the stuff that never runs during the benchmarks */
	sys_getgid,
	sys_setuid,
	sys_setgid,
	sys_geteuid,
	sys_getegid,
	sys_setpgid,
	sys_getppid,
	sys_getpgrp,
	/* 112 */
	sys_setsid,
	sys_setreuid,
	sys_setregid,
	sys_getgroups,
	sys_setgroups,
	sys_setresuid,
	sys_getresuid,
	sys_setresgid,
	/* 120 */
	sys_getresgid,
	sys_getpgid,
	sys_setfsuid,
	sys_setfsgid,
	sys_getsid,
	sys_capget,
	sys_capset,
	/* 127 */
	sys_rt_sigpending,
	sys_rt_sigtimedwait,
	sys_rt_sigqueueinfo,
	sys_rt_sigsuspend,
	stub_sigaltstack,
	sys_utime,
	sys_mknod,
/* Only needed for a.out */
	sys_ni_syscall,
	sys_personality,
	/* 136 */
	sys_ustat,
	sys_statfs,
	sys_fstatfs,
	sys_sysfs,
	/* 140 */
	sys_getpriority,
	sys_setpriority,
	sys_sched_setparam,
	sys_sched_getparam,
	sys_sched_setscheduler,
	sys_sched_getscheduler,
	sys_sched_get_priority_max,
	sys_sched_get_priority_min,
	sys_sched_rr_get_interval,
	/* 149 */
	sys_mlock,
	sys_munlock,
	sys_mlockall,
	sys_munlockall,
	/* 153 */
	sys_vhangup,
	/* 154 */
	sys_modify_ldt,
	/* 155 */
	sys_pivot_root,
	/* 156 */
	sys_sysctl,
	/* 157 */
	sys_prctl,
	sys_arch_prctl,
	/* 159 */
	sys_adjtimex,
	/* 160 */
	sys_setrlimit,
	/* 161 */
	sys_chroot,
	/* 162 */
	sys_sync,
	/* 163 */
	sys_acct,
	/* 164 */
	sys_settimeofday,
	/* 165 */
	sys_mount,
	sys_umount,
	/* 167 */
	sys_swapon,
	sys_swapoff,
	/* 169 */
	sys_reboot,
	/* 170 */
	sys_sethostname,
	sys_setdomainname,
	/* 172 */
	stub_iopl,
	sys_ioperm,
	/* 174 */
	sys_ni_syscall,
	sys_init_module,
	sys_delete_module,
	sys_ni_syscall,
	sys_ni_syscall,
	/* 179 */
	sys_quotactl,
	/* 180 */
	sys_nfsservctl,
/* reserved for LiS/STREAMS */
	sys_ni_syscall,
	sys_ni_syscall,
/* reserved for AFS */
	sys_ni_syscall,
/* reserved for tux */
	sys_ni_syscall,
	/* 185 */
	sys_ni_syscall,
	/* 186 */
	sys_gettid,
	/* 187 */
	sys_readahead,
	sys_setxattr,
	sys_lsetxattr,
	sys_fsetxattr,
	sys_getxattr,
	sys_lgetxattr,
	sys_fgetxattr,
	sys_listxattr,
	sys_llistxattr,
	sys_flistxattr,
	sys_removexattr,
	sys_lremovexattr,
	sys_fremovexattr,
	sys_tkill,
	sys_time,
	sys_futex,
	sys_sched_setaffinity,
	sys_sched_getaffinity,
	sys_ni_syscall)	/* use arch_prctl */
	sys_io_setup,
	sys_io_destroy,
	sys_io_getevents,
	sys_io_submit,
	sys_io_cancel,
	sys_ni_syscall)	/* use arch_prctl */
	sys_lookup_dcookie,
	sys_epoll_create,
	sys_ni_syscall,
	sys_ni_syscall,
	sys_remap_file_pages,
	sys_getdents64,
	sys_set_tid_address,
	sys_restart_syscall,
	sys_semtimedop,
	sys_fadvise64,
	sys_timer_create,
	sys_timer_settime,
	sys_timer_gettime,
	sys_timer_getoverrun,
	sys_timer_delete,
	sys_clock_settime,
	sys_clock_gettime,
	sys_clock_getres,
	sys_clock_nanosleep,
	sys_exit_group,
	sys_epoll_wait,
	sys_epoll_ctl,
	sys_tgkill,
	sys_utimes,
	sys_ni_syscall,
	sys_mbind,
	sys_set_mempolicy,
	sys_get_mempolicy,
	sys_mq_open,
	sys_mq_unlink,
	sys_mq_timedsend,
	sys_mq_timedreceive,
	sys_mq_notify,
	sys_mq_getsetattr,
	sys_kexec_load,
	sys_waitid,
	sys_add_key,
	sys_request_key,
	sys_keyctl,
	sys_ioprio_set,
	sys_ioprio_get,
	sys_inotify_init,
	sys_inotify_add_watch,
	sys_inotify_rm_watch,
	sys_migrate_pages,
	sys_openat,
	sys_mkdirat,
	sys_mknodat,
	sys_fchownat,
	sys_futimesat,
	sys_newfstatat,
	sys_unlinkat,
	sys_renameat,
	sys_linkat,
	sys_symlinkat,
	sys_readlinkat,
	sys_fchmodat,
	sys_faccessat,
	sys_pselect6,
	sys_ppoll,
	sys_unshare,
	sys_set_robust_list,
	sys_get_robust_list,
	sys_splice,
	sys_tee,
	sys_sync_file_range,
	sys_vmsplice,
	sys_move_pages,
	sys_utimensat,
	sys_epoll_pwait,
	sys_signalfd,
	sys_timerfd_create,
	sys_eventfd,
	sys_fallocate,
	sys_timerfd_settime,
	sys_timerfd_gettime,
	sys_accept4,
	sys_signalfd4,
	sys_eventfd2,
	sys_epoll_create1,
	sys_dup3,
	sys_pipe2,
	sys_inotify_init1,
	sys_preadv,
	sys_pwritev,
	sys_rt_tgsigqueueinfo,
	sys_perf_event_open,
	sys_recvmmsg,
	sys_fanotify_init,
	sys_fanotify_mark,
	sys_prlimit64,
	sys_name_to_handle_at,
	sys_open_by_handle_at,
	sys_clock_adjtime,
	/* 306 */
	sys_syncfs,
	sys_sendmmsg,
	sys_setns,
