#
############################################################################
# (C) Copyright 2008 Novell, Inc. All Rights Reserved.
#
#  GPLv2: This program is free software; you can redistribute it
#  and/or modify it under the terms of version 2 of the GNU General
#  Public License as published by the Free Software Foundation.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
############################################################################

#LIBS += /usr/local/include/readline
#LIBS += /Users/taysom/src/readline-6.1/shlib/readline.so
#LIBS += /usr/lib/libreadline.dylib
include ../../mk/default.mk
LIBS += -lq
##os := $(system uname)
##ifeq ($(os),Linux)
##	LIBS += -lreadline
##else ifeq ($(os),Darwin)
##	LIBS += /usr/lib/libreadline.dylib
##else
##	LIBS += -lxyzzy
##endif
#LIBS += -lreadline
